### ISSUE TITLE
Songs not working on Oculus Quest

### ISSUE THREAD

**Issue by S3ri0us97** [joshwcomeau/beatmapper#103]
Created songs can't be uploaded to Oculus Quest.
figured out that it has to do something with the map files (e.g. Expert.dat).
I tried some Songs on Beat Saver created with Beatmapper and they also didn't worked.

![BMBF Error](https://user-images.githubusercontent.com/67964476/86794331-ac6c4880-c06c-11ea-96d6-eab80128d10b.png)

**Comment by murapix** [comment]
This is because you didn't properly convert your audio file into an ogg. Beatmapper will accept any file with the `.ogg` extension, but it doesn't fully check if that file is *actually* an ogg.

Changing the extension from `.mp3` or `.flac` or whatever to `.ogg` doesn't change it to an ogg, it's still the old format. Same with many online converters, they might look like oggs, but there tends to be some issue with the formatting they use. The only tried-and-true method we over at the Beat Saber Modding Group discord know is to use Audacity, and we've got good instructions on how to do that here on the [BSMG wiki](https://bsmg.wiki/mapping/basic-audio.html#audio-setup-quick-start)
