### ISSUE TITLE
Selection Sidebar Improvements - Forward/Backward and Cut/Copy/Paste Buttons

### ISSUE THREAD

**Issue by murapix** [joshwcomeau/beatmapper#30]
Being able to flip the selected notes is good, and I know you can cut, copy, and paste using the standard keybinds, but it would be nice to be able to shift notes forwards and backwards as well, in the case of mistiming or even just accidental misplacement.
Aside from that, having buttons for cut, copy, and paste is generally a good idea, for those who don't realize the functionality already exists or somehow don't know those standard hotkeys.

**Comment by joshwcomeau** [comment]
Yeah, I've been trying to add buttons for all keyboard shortcuts. Cut/copy/paste feel kinda obvious, but I imagine there are people who wouldn't try it because they assume it'd only be for text in the browser. I can add those buttons to the selection panel.

Shifting notes forwards/backwards... That's an interesting idea. I'll add it to the list of stuff to try - I'm trying to be pretty conservative with new features, since every new thing increases the amount of UI clutter / shortcuts to learn. But maybe this'd be a significant quality-of-life boost. Do other editors have this / has it been useful for you?

**Comment by murapix** [comment]
It's just a QoL enhancement I thought of when touching up my song's offset again, no idea what really any other editors have.

**Comment by Red5d** [comment]
I think this would be really useful too. When I'm tweaking the timing on groups of blocks or even individual "frames", It'd be nice to be able to shift them one "frame" forward or back at a time rather than select blocks, Ctrl-X, move to position, Ctrl-V.

**Comment by joshwcomeau** [comment]
Yeah, fair point. I was in this situation myself as well, trying to move obstacles. Will add little buttons and keyboard shortcuts shortly :)

**Comment by joshwcomeau** [comment]
Added forwards/backwards buttons :D 

Two new buttons show up in the side-panel with an active selection, and the keyboard shortcut is `alt+↑` and `alt+↓`. I'm also going to ship the ability to hold alt and spin the mousewheel. Will leave the issue open until that additional change, let me know what y'all think of it!

I didn't add copy/paste, but now that I have proper [keyboard shortcut](https://beatmapper.app/docs/keyboard-shortcuts) documentation, I don't feel like it's as necessary.

**Comment by joshwcomeau** [comment]
Added the mousewheel shortcut as well! Closing this issue. Still open for feedback though @murapix @Red5d
