### ISSUE TITLE
Japanese characters in the map title won't allow the song to load

### ISSUE THREAD

**Issue by lyokofirelyte** [joshwcomeau/beatmapper#50]
Here's a quick video of it not loading: https://imgur.com/a/yrpLhZr

Looking in the DOM it looks like it just doesn't receive any HTML to display if there's unknown characters in the title. There's also no errors in the console when it won't load.
![image](https://user-images.githubusercontent.com/4260126/68534157-b16ad380-02f6-11ea-8726-badb31eed60a.png)

**Comment by joshwcomeau** [comment]
Ah, that's strange! My bet is that because I use the song name as the key in the browser's built-in database, that database probably doesn't support all of UTF-8.

While I figure out a workaround, probably best for you to stick with English placeholder names, and edit the .dat file when you're done (you'll want to change `_songName` in info.dat in the downloaded .zip)

**Comment by lyokofirelyte** [comment]
Thanks for the reply, I feel silly I didn't think of changing the name after exporting the file!
