### ISSUE TITLE
When I click, it makes multiple blocks in the same spot.

### ISSUE THREAD

**Issue by henwill8** [joshwcomeau/beatmapper#57]
Just suddenly, it has been making multiple blocks facing the same or different direction, causing a lot of lag. It creates so much lag that moving forward or backwards one beat takes up to 10 seconds each. This is probably because it is making one block for the direction on the side and then one to whichever direction my mouse is.

**Comment by joshwcomeau** [comment]
ah, sorry I missed this comment!

Can you share a screen recording, or maybe some more detailed instructions for how I could reproduce this? I haven't seen it myself, but possibly I'm creating notes in a different way

**Comment by henwill8** [comment]
So as I was doing it, a different multiple placement type thing happened, which was the second one where they appeared at different spots. At the time of opening this issue, the first one in the video where multiple are in the same block was happening pretty much every time I tried to place a block, but is happening less frequently now.
![simplescreenrecorder-2019-11-16_19 06 30](https://user-images.githubusercontent.com/43818215/69001997-48123400-08a5-11ea-9bb2-7d062e99ee91.gif)

**Comment by henwill8** [comment]
I have been messing around with it more and it seems that it happens mostly on the offbeats, (not whole beats or half beats) so maybe it is something with rounding.

**Comment by joshwcomeau** [comment]
Right, yeah so this is an annoying issue that has plagued me off and on since I started this project x_x. There are a bunch of contributing factors (including the issues with offsets, floating point number precision issues, and the conversions between beats and real time)

Thinking I might go for the "nuclear" option and always constrain notes to the nearest 1/72nd note, which I think is the lowest common multiple for all valid snapping options. Though I don't know if that'll fix all my problems... I'll dig.

> Oh, and a side question, is it possible to run lightmap on beatmapper?

I'm not familiar with Lightmap, but it should be! Presumably you can download your map from Beatmapper, run whatever program you like on that map to generate the lights, and then re-import it in Beatmapper (it _should_ prompt you to overwrite it but tbh I haven't tested it in a while. You can always delete the original first)

**Comment by joshwcomeau** [comment]
@henwill8 ok, so I think I solved the original issue, of slight rounding problems for 1/3rd notes.

I haven't been able to replicate that second issue you highlighted, where it seems to add a block to a previous time in the song o_O

Let me know if this fixes those issues!

**Comment by henwill8** [comment]
Just tried it and it works fine now, great job!
