### ISSUE TITLE
Can't import map.

### ISSUE THREAD

**Issue by henwill8** [joshwcomeau/beatmapper#73]
I have followed all of the things needed but still can't import this map.
[d-e-c-a-d-e_20191125T1412.legacy.zip](https://github.com/joshwcomeau/beatmapper/files/3888784/d-e-c-a-d-e_20191125T1412.legacy.zip)
Also, amazing work on the editor, I would definitely donate if I could... 
Edit: Side question, are you planning on adding online editing? (Being able to edit with a friend)

**Comment by joshwcomeau** [comment]
hey @henwill8,

Thanks for the kind words, sorry you've been having trouble with it!

I found the issue and a fix is deploying now, should be up in 5 minutes. You might have to do a hard refresh (cmd + R on a mac, ctrl+shift+R on Windows) to fetch the latest version.

That said, I'm considering deprecating "legacy" imports and exports. When I added that feature several months ago, MediocreMapper was still outputting V1 files, and most mappers were doing the conversion themselves. I believe MediocreMapper mk5 (and definitely the more recent forks) support v2 format. All of this to say: if you have other legacy maps on your computer, I suggest importing them into Beatmapper and exporting V2 (the default non-legacy), so that you aren't stuck if I do remove legacy imports/exports

> Edit: Side question, are you planning on adding online editing? (Being able to edit with a friend)

Not currently. It's a neat idea but _a lot_ of work, and not something I'd personally want to use.

**Comment by joshwcomeau** [comment]
(Closing, since I was able to import it myself locally, but let me know if it still gives you problems!)

**Comment by henwill8** [comment]
@joshwcomeau I noticed you have a discord, could I join it to make it easier to report small bugs to you?

**Comment by joshwcomeau** [comment]
@henwill8 Github issues are the best way to make sure I keep track of potential problems :) I get email notifications about them, and I'm not actually that active in Discord.

You should definitely join the discord anyway though, it's a good way to meet other mappers, get feedback on your maps, etc: https://discordapp.com/invite/beatsabermods
